apiVersion: v1
kind: Service
metadata:
  name: myapp 
spec:
  ports:
  - name: sample-http 
    port: 80 
    protocol: TCP
    targetPort: 80 
    nodePort: 30081
  selector:
    app.kubernetes.io/name: myapp 
  type: NodePort 
